-
  name: upgrade all packages
  hosts: target1
  tasks:
  - name: patch update
    yum:
     name: '*'
     state: latest
    become: yes
  - name: remove the Apache package
    yum:
     name: httpd
     state: absent
    become: yes
