-
  name: examples for service module
  hosts: target1
  become: yes
  tasks:
    - name: Start service httpd, if not started
      service:
       name: httpd
       state: started

    - name: Stop service httpd, if started
      service:
       name: httpd
       state: stopped

    - name: Restart service httpd, in all cases
      service:
       name: httpd
       state: restarted

    - name: Reload service httpd, in all cases
      service:
       name: httpd
       state: reloaded

    - name: Enable service httpd, and not touch the state
      service:
       name: httpd
       enabled: yes
